### PR TITLE
Added timestamp-based update

### PR DESCRIPTION
**Pull request by smspence**

### CODE REVIEW

**Comment by austinpray** [comment]
Whoops! Format check failed 

Go files must be formatted with gofmt. Please run:
  gofmt -w /home/travis/gopath/src/github.com/liveplant/liveplant-server/main.go

**Comment by smspence** [comment]
Done!

**Comment by austinpray** [comment]
@smspence Looks like this isn't working on https://liveplant.herokuapp.com/votes

The values never get reset

**Comment by smspence** [comment]
Did you call GET /current_action before calling GET /votes?

The update() call happens inside GetCurrentAction().  The assumption is that the robot is going to be calling GetCurrentAction() all the time, and that is what "turns the crank" on our update logic.

Is this desired behavior?  If not, I guess we could just think of some other way to periodically fire off the update() function.

**Comment by austinpray** [comment]
@smspence it should definitely reset based on calls to `/votes`. Couple reasons:
- If nobody is making calls to `/votes`, nobody is on the website voting and the robot shouldn't be doing anything. "If a tree falls in the forest..."
- One should be able to work on the front-end without a real robot calling the endpoint
- Avoids race conditions where the client and robot's polling is slightly out of sync. The `votes` endpoint will always have accurate information regardless of the behavior of the robot.

**Pull request merged**
